### Register a User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test@gmail.com",
    "password": "Pa$$word1",
    "role": "User"
}

### Login a User
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "Pa$$word1"
}

###GET LOGGED IN USER PROFILE
GET http://localhost:5000/api/auth/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwibmFtZSI6InRlc3QiLCJuYW1laWQiOiI3MWFjMThkOC0wODYxLTRhMWUtODBlZS1lZjI4YjZlOWIxZGIiLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQyMDAiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAiLCJyb2xlIjoiVXNlciIsIm5iZiI6MTczMzg3Mzk5MSwiZXhwIjoxNzMzODc3NTkxLCJpYXQiOjE3MzM4NzM5OTF9.v5bAxh9CnVbLboctT2S7OtwNpRFqocHFjbLPoUWYZVM